const selectCountries = () => {
    return `
    <!-- All countries -->
    <select id="country" name="country" onchange="window.setCountry(this.value)">
        <option>Selecione o seu país</option>
        <option value="AF">Afeganistão</option>
        <option value="AX">Ilhas Aland</option>
        <option value="AL">Albânia</option>
        <option value="DZ">Argélia</option>
        <option value="AS">Samoa Americana</option>
        <option value="AD">Andorra</option>
        <option value="AO">Angola</option>
        <option value="AI">Anguilla</option>
        <option value="AQ">Antártica</option>
        <option value="AG">Antigua e Barbuda</option>
        <option value="AR">Argentina</option>
        <option value="AM">Armênia</option>
        <option value="AW">Aruba</option>
        <option value="AU">Austrália</option>
        <option value="AT">Áustria</option>
        <option value="AZ">Azerbaijão</option>
        <option value="BS">Bahamas</option>
        <option value="BH">Bahrain</option>
        <option value="BD">Bangladesh</option>
        <option value="BB">Barbados</option>
        <option value="BY">Bielo-Rússia</option>
        <option value="BE">Bélgica</option>
        <option value="BZ">Belize</option>
        <option value="BJ">Benin</option>
        <option value="BM">Bermudas</option>
        <option value="BT">Butão</option>
        <option value="BO">Bolívia</option>
        <option value="BQ">Bonaire, Sint Eustatius e Saba</option>
        <option value="BA">Bósnia e Herzegovina</option>
        <option value="BW">Botswana</option>
        <option value="BV">Ilha Bouvet</option>
        <option value="BR">Brasil</option>
        <option value="IO">Território Britânico do Oceano Índico</option>
        <option value="BN">Brunei Darussalam</option>
        <option value="BG">Bulgária</option>
        <option value="BF">Burkina Faso</option>
        <option value="BI">Burundi</option>
        <option value="KH">Camboja</option>
        <option value="CM">Camarões</option>
        <option value="CA">Canadá</option>
        <option value="CV">cabo Verde</option>
        <option value="KY">Ilhas Cayman</option>
        <option value="CF">República Centro-Africana</option>
        <option value="TD">Chade</option>
        <option value="CL">Chile</option>
        <option value="CN">China</option>
        <option value="CX">Ilha do Natal</option>
        <option value="CC">Ilhas Cocos (Keeling)</option>
        <option value="CO">Colômbia</option>
        <option value="KM">Comores</option>
        <option value="CG">Congo</option>
        <option value="CD">Congo, República Democrática do Congo</option>
        <option value="CK">Ilhas Cook</option>
        <option value="CR">Costa Rica</option>
        <option value="CI">Cote D'Ivoire</option>
        <option value="HR">Croácia</option>
        <option value="CU">Cuba</option>
        <option value="CW">Curaçao</option>
        <option value="CY">Chipre</option>
        <option value="CZ">República Checa</option>
        <option value="DK">Dinamarca</option>
        <option value="DJ">Djibouti</option>
        <option value="DM">Dominica</option>
        <option value="DO">República Dominicana</option>
        <option value="EC">Equador</option>
        <option value="EG">Egito</option>
        <option value="SV">El Salvador</option>
        <option value="GQ">Guiné Equatorial</option>
        <option value="ER">Eritreia</option>
        <option value="EE">Estônia</option>
        <option value="ET">Etiópia</option>
        <option value="FK">Ilhas Falkland (Malvinas)</option>
        <option value="FO">ilhas Faroe</option>
        <option value="FJ">Fiji</option>
        <option value="FI">Finlândia</option>
        <option value="FR">França</option>
        <option value="GF">Guiana Francesa</option>
        <option value="PF">Polinésia Francesa</option>
        <option value="TF">Territórios Franceses do Sul</option>
        <option value="GA">Gabão</option>
        <option value="GM">Gâmbia</option>
        <option value="GE">Georgia</option>
        <option value="DE">Alemanha</option>
        <option value="GH">Gana</option>
        <option value="GI">Gibraltar</option>
        <option value="GR">Grécia</option>
        <option value="GL">Groenlândia</option>
        <option value="GD">Grenada</option>
        <option value="GP">Guadalupe</option>
        <option value="GU">Guam</option>
        <option value="GT">Guatemala</option>
        <option value="GG">Guernsey</option>
        <option value="GN">Guiné</option>
        <option value="GW">Guinea-bissau</option>
        <option value="GY">Guiana</option>
        <option value="HT">Haiti</option>
        <option value="HM">Ilha Heard e Ilhas McDonald</option>
        <option value="VA">Santa Sé (Estado da Cidade do Vaticano)</option>
        <option value="HN">Honduras</option>
        <option value="HK">Hong Kong</option>
        <option value="HU">Hungria</option>
        <option value="IS">Islândia</option>
        <option value="IN">Índia</option>
        <option value="ID">Indonésia</option>
        <option value="IR">Irã (Republic Islâmica do Irã</option>
        <option value="IQ">Iraque</option>
        <option value="IE">Irlanda</option>
        <option value="IM">Ilha de Man</option>
        <option value="IL">Israel</option>
        <option value="IT">Itália</option>
        <option value="JM">Jamaica</option>
        <option value="JP">Japão</option>
        <option value="JE">Jersey</option>
        <option value="JO">Jordânia</option>
        <option value="KZ">Cazaquistão</option>
        <option value="KE">Quênia</option>
        <option value="KI">Kiribati</option>
        <option value="KP">Coréia, República Popular Democrática da</option>
        <option value="KR">Republica da Coréia</option>
        <option value="XK">Kosovo</option>
        <option value="KW">Kuwait</option>
        <option value="KG">Quirguistão</option>
        <option value="LA">República Democrática Popular do Laos</option>
        <option value="LV">Letônia</option>
        <option value="LB">Líbano</option>
        <option value="LS">Lesoto</option>
        <option value="LR">Libéria</option>
        <option value="LY">Jamahiriya Árabe da Líbia</option>
        <option value="LI">Liechtenstein</option>
        <option value="LT">Lituânia</option>
        <option value="LU">Luxemburgo</option>
        <option value="MO">Macau</option>
        <option value="MK">Macedônia, Antiga República Iugoslava da</option>
        <option value="MG">Madagáscar</option>
        <option value="MW">Malawi</option>
        <option value="MY">Malásia</option>
        <option value="MV">Maldivas</option>
        <option value="ML">Mali</option>
        <option value="MT">Malta</option>
        <option value="MH">Ilhas Marshall</option>
        <option value="MQ">Martinica</option>
        <option value="MR">Mauritânia</option>
        <option value="MU">Maurício</option>
        <option value="YT">Mayotte</option>
        <option value="MX">México</option>
        <option value="FM">Micronésia, Estados Federados da</option>
        <option value="MD">Moldávia, República da</option>
        <option value="MC">Mônaco</option>
        <option value="MN">Mongólia</option>
        <option value="ME">Montenegro</option>
        <option value="MS">Montserrat</option>
        <option value="MA">Marrocos</option>
        <option value="MZ">Moçambique</option>
        <option value="MM">Myanmar</option>
        <option value="NA">Namibia</option>
        <option value="NR">Nauru</option>
        <option value="NP">Nepal</option>
        <option value="NL">Países Baixos</option>
        <option value="AN">Antilhas Holandesas</option>
        <option value="NC">Nova Caledônia</option>
        <option value="NZ">Nova Zelândia</option>
        <option value="NI">Nicarágua</option>
        <option value="NE">Níger</option>
        <option value="NG">Nigéria</option>
        <option value="NU">Niue</option>
        <option value="NF">Ilha Norfolk</option>
        <option value="MP">Ilhas Marianas do Norte</option>
        <option value="NO">Noruega</option>
        <option value="OM">Omã</option>
        <option value="PK">Paquistão</option>
        <option value="PW">Palau</option>
        <option value="PS">Território Palestino, Ocupado</option>
        <option value="PA">Panamá</option>
        <option value="PG">Papua Nova Guiné</option>
        <option value="PY">Paraguai</option>
        <option value="PE">Peru</option>
        <option value="PH">Filipinas</option>
        <option value="PN">Pitcairn</option>
        <option value="PL">Polônia</option>
        <option value="PT">Portugal</option>
        <option value="PR">Porto Rico</option>
        <option value="QA">Catar</option>
        <option value="RE">Reunião</option>
        <option value="RO">Romênia</option>
        <option value="RU">Federação Russa</option>
        <option value="RW">Ruanda</option>
        <option value="BL">São Bartolomeu</option>
        <option value="SH">Santa Helena</option>
        <option value="KN">São Cristóvão e Neves</option>
        <option value="LC">Santa Lúcia</option>
        <option value="MF">são Martinho</option>
        <option value="PM">São Pedro e Miquelão</option>
        <option value="VC">São Vicente e Granadinas</option>
        <option value="WS">Samoa</option>
        <option value="SM">San Marino</option>
        <option value="ST">São Tomé e Príncipe</option>
        <option value="SA">Arábia Saudita</option>
        <option value="SN">Senegal</option>
        <option value="RS">Sérvia</option>
        <option value="CS">Sérvia e Montenegro</option>
        <option value="SC">Seychelles</option>
        <option value="SL">Serra Leoa</option>
        <option value="SG">Cingapura</option>
        <option value="SX">St Martin</option>
        <option value="SK">Eslováquia</option>
        <option value="SI">Eslovênia</option>
        <option value="SB">Ilhas Salomão</option>
        <option value="SO">Somália</option>
        <option value="ZA">África do Sul</option>
        <option value="GS">Geórgia do Sul e Ilhas Sandwich do Sul</option>
        <option value="SS">Sudão do Sul</option>
        <option value="ES">Espanha</option>
        <option value="LK">Sri Lanka</option>
        <option value="SD">Sudão</option>
        <option value="SR">Suriname</option>
        <option value="SJ">Svalbard e Jan Mayen</option>
        <option value="SZ">Suazilândia</option>
        <option value="SE">Suécia</option>
        <option value="CH">Suíça</option>
        <option value="SY">República Árabe da Síria</option>
        <option value="TW">Taiwan, província da China</option>
        <option value="TJ">Tajiquistão</option>
        <option value="TZ">Tanzânia, República Unida da</option>
        <option value="TH">Tailândia</option>
        <option value="TL">Timor-Leste</option>
        <option value="TG">Ir</option>
        <option value="TK">Tokelau</option>
        <option value="TO">Tonga</option>
        <option value="TT">Trinidad e Tobago</option>
        <option value="TN">Tunísia</option>
        <option value="TR">Peru</option>
        <option value="TM">Turcomenistão</option>
        <option value="TC">Ilhas Turcas e Caicos</option>
        <option value="TV">Tuvalu</option>
        <option value="UG">Uganda</option>
        <option value="UA">Ucrânia</option>
        <option value="AE">Emirados Árabes Unidos</option>
        <option value="GB">Reino Unido</option>
        <option value="US">Estados Unidos</option>
        <option value="UM">Ilhas Menores Distantes dos Estados Unidos</option>
        <option value="UY">Uruguai</option>
        <option value="UZ">Uzbequistão</option>
        <option value="VU">Vanuatu</option>
        <option value="VE">Venezuela</option>
        <option value="VN">Viet Nam</option>
        <option value="VG">Ilhas Virgens Britânicas</option>
        <option value="VI">Ilhas Virgens, EUA</option>
        <option value="WF">Wallis e Futuna</option>
        <option value="EH">Saara Ocidental</option>
        <option value="YE">Iémen</option>
        <option value="ZM">Zâmbia</option>
        <option value="ZW">Zimbábue</option>
    </select>`;
}

export default selectCountries;